name: Npm RT Publish

on:
  push:
    tags:
      - v**-rt

jobs:
  publish:
    name: Build And Publish
    runs-on: ubuntu-latest
    steps:
      - name: Get Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Build
        run: npm run build:rt

      - name: Publish
        run: cd packages/rt && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
